### PR TITLE
add contextual prompts for RAG prompts

### PR DESCRIPTION
**Pull request by fengsh27**
### Abstract
This submission was to showcase the injected RAG contextual prompts.

### CODE REVIEW

**Comment by slobentanzer** [comment]
Thanks! I am not able to build the docker compose, yarn fails with:
```
23.78 - info Linting and checking validity of types...
25.47 
25.47 Failed to compile.
25.47 
25.47 ./app/components/chat.tsx
25.47 191:17  Error: Missing "key" prop for element in iterator  react/jsx-key
25.47 
25.47 ./app/components/kg.tsx
25.47 63:6  Warning: React Hook useEffect has a missing dependency: 'updateConnectionStatus'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
25.47 
25.47 ./app/components/rag-contextual-prompts-modal.tsx
25.47 22:13  Error: Missing "key" prop for element in iterator  react/jsx-key
25.47 
25.47 ./app/components/rag.tsx
25.47 104:6  Warning: React Hook useEffect has a missing dependency: 'updateConnectionStatus'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
25.47 
25.47 info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
25.53 error Command failed with exit code 1.
25.53 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1
```

**Comment by fengsh27** [comment]
@sebeier I'll have a look

**Comment by fengsh27** [comment]
@slobentanzer fixed, please have a try.

**Comment by slobentanzer** [comment]
@fengsh27 FYI I added a version info to the about page, mainly because I want to know whether what I am looking at is in fact the most current version. It is currently hard-coded in the cn.ts and en.ts files; we should probably make that a variable at some point.

**Comment by fengsh27** [comment]
@slobentanzer I submitted the rag contextual prompts button, please have a look. 

Additionally, I updated the way to get version info in Welcome page. We can bump version by updating `package.version` in `src-tauri/tauri.conf.json`.

**Review by slobentanzer — APPROVED** [review]
Great job!

**Pull request merged**
