### PR TITLE
feat: support OncoKB api agent and auto agent selector

### PR DESCRIPTION
**Pull request by fengsh27**

### CODE REVIEW

**Comment by slobentanzer** [comment]
@fengsh27 thanks! I updated `biochatter-server` to 0.4.0 and deployed the docker compose. Have two questions:

1. OncoKB (manual selection) and Auto mode do not seem to trigger; I get a regular response from the model without any RAG.
2. This being a PR to the main biochatter-next repo, we should not constrain to the specific use case (cancer genetics for instance). It is fine for testing, but the additions to the main repo should always conserve the generic nature of the app. The customisations are to be implemented elsewhere. (Ideally, we would run the cancer genetics use case in the `cancer-genetics` BioCypher repository, with all configuration there.)

**Comment by slobentanzer** [comment]
@fengsh27 it would also be great if the app gave some simple feedback on what it is doing, such as `Auto mode: selecting tool`, `Auto mode: selected knowledge graph`, `Generating query`, `Reflecting on query`, etc.

**Comment by fengsh27** [comment]
> @fengsh27 thanks! I updated `biochatter-server` to 0.4.0 and deployed the docker compose. Have two questions:
> 
> 1. OncoKB (manual selection) and Auto mode do not seem to trigger; I get a regular response from the model without any RAG.
> 2. This being a PR to the main biochatter-next repo, we should not constrain to the specific use case (cancer genetics for instance). It is fine for testing, but the additions to the main repo should always conserve the generic nature of the app. The customisations are to be implemented elsewhere. (Ideally, we would run the cancer genetics use case in the `cancer-genetics` BioCypher repository, with all configuration there.)

@slobentanzer 
Regarding 1. biochatter-server changes are not submitted yet, I will raise PR for biochatter-server's change later
Regarding 2. do you mean it is not appropriate to submit biochatter-next.yaml changes here?

**Comment by fengsh27** [comment]
> @fengsh27 it would also be great if the app gave some simple feedback on what it is doing, such as `Auto mode: selecting tool`, `Auto mode: selected knowledge graph`, `Generating query`, `Reflecting on query`, etc.

Good suggestion. I think we can resolve it in next PR. 
Can we show these information in Rag Contextual Prompts dialog

**Comment by slobentanzer** [comment]
@fengsh27 since this PR depends on changes to `biochatter-server`, do you want to wait for these?

**Comment by fengsh27** [comment]
> @fengsh27 since this PR depends on changes to `biochatter-server`, do you want to wait for these?

No problem, I'm OK with that

**Comment by fengsh27** [comment]
@slobentanzer I added support of example usage in Welcome page. Please have a look and modify `Example` content which I will apply to our BioChatter-Next server

**Comment by fengsh27** [comment]
Are we ready to merge this PR?

**Comment by slobentanzer** [comment]
Does it work on your end, including my recent changes? If so, then yes.

**Comment by fengsh27** [comment]
Yes, it works well on my end

**Pull request merged**
