### PR TITLE
Update main color with biocypher logo

### PR DESCRIPTION
**Pull request by Wang-Cankun**

### CODE REVIEW

**Comment by slobentanzer** [comment]
Hi @Wang-Cankun,
thanks! I have created a new logo for BioChatter (to differentiate from BioCypher), which I attach here (so the main colour maybe should be something else, have to check). Do you know an easy way (program) to generate the various icon files included in this repo (`changes/public`) from the base PNG?

biochatter_logo

**Comment by Wang-Cankun** [comment]
> Hi @Wang-Cankun, thanks! I have created a new logo for BioChatter (to differentiate from BioCypher), which I attach here (so the main colour maybe should be something else, have to check). Do you know an easy way (program) to generate the various icon files included in this repo (`changes/public`) from the base PNG?
> 
> biochatter_logo

I created a short script here: https://gist.github.com/Wang-Cankun/0e0b9667a1b7eb49ab3614e3b732d400

**Comment by slobentanzer** [comment]
Thanks! I don't commonly use JS, how do I run this with the least effort?

**Comment by Wang-Cankun** [comment]
Updated gist with a short tutorial: https://gist.github.com/Wang-Cankun/0e0b9667a1b7eb49ab3614e3b732d400?permalink_comment_id=4899836#gistcomment-4899836

**Comment by slobentanzer** [comment]
Nice, thanks!

**Pull request closed without merging**
